### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by PascalBureau** [cnigfr/schema-accessibilite-voirie#56]
Ceci est enfin le test ! Mais toutes les pages sont en anglais.

**Comment by GT-CNIG-DDU** [comment]
Bravo Pascal, tu as désormais le statut de collaborateur du Github !

**Comment by PascalBureau** [comment]
Merci mais tous les onglets et info sont en anglais.
Peut-on et par où passer, avoir accès à l'origine des standards ? je ne les vois pas ??
Pascal




Pascal Bureau, 06 26 18 83 88

Représentant du CA à la CACUN du CNCPH & à la DMA

(Représentant du Conseil d'Administration à la Commission Accessibilité, Conception Universelle et Numérique du Conseil National Consultatif des Personnes Handicapées & à la Délégation Ministérielle à l'Accessibilité)


https://www.apf-francehandicap.org/

[cid:8a1f6185-344d-4ac3-b283-4a4adca68e1b]

Droit à la déconnexion : tout mail reçu en dehors de vos horaires de travail n'appelle pas de réponse immédiate

http://www.reflexe-handicap.org<http://www.reflexe-handicap.org/>

http://vos-droits.apf.asso.fr/
http://www.cfhe.org/
http://www.apf.asso.fr/footer-informations-thematiques/footer-aides-techniques
http://www.vacances-accessibles.apf.asso.fr/
http://apfevasion.blogs.apf.asso.fr/
http://www.apf-entreprises.fr<http://www.apf-entreprises.fr/>



[cid:c6aaf87b-1e3d-4182-818c-5a1b1ecca17c]
________________________________
De : GT CNIG DDU ***@***.***>
Envoyé : lundi 7 octobre 2024 15:03
À : cnigfr/schema-accessibilite-voirie ***@***.***>
Cc : Pascal BUREAU ***@***.***>; Author ***@***.***>
Objet : Re: [cnigfr/schema-accessibilite-voirie] Test (Issue #56)


ATTENTION : Cet e-mail provient d'une personne externe à l'association. Ne cliquez pas sur les liens ou n'ouvrez pas les pièces jointes si vous ne connaissez pas l'expéditeur et que vous n'êtes pas sûr de son contenu.

Bravo Pascal, tu as désormais le statut de collaborateur du Github !

**Comment by GT-CNIG-DDU** [comment]
La version en vigueur (publiée) standard et la version courante du projet d'évolution du standard [sont ici](https://github.com/cnigfr/schema-accessibilite-voirie/tree/main/Standard).
