### ISSUE TITLE
changer nom attribut covisibilite

### ISSUE THREAD

**Issue by Marion-Torterotot** [cnigfr/schema-accessibilite-voirie#6]
Dans la classe TRAVERSEE, je propose de changer le nom de l'attribut covisibilite par masqueCovisibilite pour limiter les erreurs d'interprétation lors de la collecte et de l'analyse.
En effet, les réponses possibles à cet attribut concernent plutôt les masques et notamment le code "01 - aucun" qui pourrait laisser penser qu'il n'y a aucune covisibilité, donc qu'elle est mauvaise, alors qu'en fait c'est qu'il n'y a aucun masque à la covisibilité, donc qu'elle est bonne.

**Comment by Claire-SARTHOU** [comment]
voir commentaire #32
